version: "3.8"
services:
  studydojo-premium:
    container_name: studydojo-premium
    build:
      context: .
      dockerfile: Dockerfile
    image: studydojo-premium:latest
    ports:
      - "8090:8090"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
