version: "3.8"
services:
  studydojo-premium:
    container_name: studydojo-spa
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '5174:5174'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true